/* ---------------------------------------------
            FRONT DESK CONSTANT
---------------------------------------------*/

export const FRONT_DESK_FEATCH_LIST = 'FRONT_DESK_FEATCH_LIST';
export const FRONT_DESK_SET_LIST = 'FRONT_DESK_SET_LIST';

export const FRONT_DESK_FEATCH_SEARCH_LIST = 'FRONT_DESK_FEATCH_SEARCH_LIST';
export const FRONT_DESK_SET_SEARCH_LIST = 'FRONT_DESK_SET_SEARCH_LIST';

export const CREATE_FRONT_DESK = 'CREATE_FRONT_DESK';
export const CREATE_FRONT_DESK_PERMITION = 'CREATE_FRONT_DESK_PERMITION';

export const GET_FRONT_DESK = 'GET_FRONT_DESK';
export const SET_FRONT_DESK = 'SET_FRONT_DESK';

export const GET_FRONT_DESK_PERMITION = 'GET_FRONT_DESK_PERMITION';
export const SET_FRONT_DESK_PERMITION = 'SET_FRONT_DESK_PERMITION';

export const UPDATE_FRONT_DESK = 'UPDATE_FRONT_DESK';
export const UPDATE_FRONT_DESK_PERMITION = 'UPDATE_FRONT_DESK_PERMITION';

