/* ---------------------------------------------
            APPOINTMENT CONSTANT
---------------------------------------------*/

export const CREATE_PATIENT = 'CREATE_PATIENT';
export const CREATE_PATIENT_SET = 'CREATE_PATIENT_SET';
export const CREATE_PATIENT_RESPONS_SET = 'CREATE_PATIENT_RESPONS_SET';
export const CREATE_PATIENT_RESPONS_RESTE = 'CREATE_PATIENT_RESPONS_RESTE';


export const CREATE_DEPENDENT = 'CREATE_DEPENDENT';
export const FEATCH_DEPENDENT = 'FEATCH_DEPENDENT';
export const SET_DEPENDENT = 'SET_DEPENDENT';
export const APPEND_DEPENDENT = 'APPEND_DEPENDENT';

export const CREATE_DEPENDENT_RESPONS = 'CREATE_DEPENDENT_RESPONS';
export const CREATE_DEPENDENT_RESPONS_RESTE = 'CREATE_DEPENDENT_RESPONS_RESTE';

export const SET_MEDICAL_HISTORY = 'SET_MEDICAL_HISTORY';
export const SAVE_MEDICAL_HISTORY = 'SAVE_MEDICAL_HISTORY';
export const RESET_MEDICAL_HISTORY = 'RESET_MEDICAL_HISTORY';

export const SEARCH_PATIENT_LIST = 'SEARCH_PATIENT_LIST';
export const SET_SEARCH_PATIENT_LIST = 'SET_SEARCH_PATIENT_LIST';

export const GET_PATIENT_DETAIL = 'GET_PATIENT_DETAIL';
export const SET_PATIENT_DETAIL = 'SET_PATIENT_DETAIL';


export const GET_APPOINTMENT_SLOT = 'GET_APPOINTMENT_SLOT';
export const SET_APPOINTMENT_SLOT = 'SET_APPOINTMENT_SLOT';
export const SET_APPOINTMENT_TOKEN = 'SET_APPOINTMENT_TOKEN';
export const RESPONS_APPOINTMENT_SLOT = 'RESPONS_APPOINTMENT_SLOT';

export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT';
export const RESPONS_BOOK_APPOINTMENT = 'RESPONS_BOOK_APPOINTMENT';
