/* ---------------------------------------------
            SUPPORT CONSTANT
---------------------------------------------*/
export const SUPPORT_LIST = 'SUPPORT_LIST';

export const SET_SUPPORT_TICKET = 'SET_SUPPORT_TICKET';

export const CREATE_SUPPORT_TICKET = 'CREATE_SUPPORT_TICKET';
export const SUPPORT_TICKET_DETAILS = 'SUPPORT_TICKET_DETAILS';
export const SET_SUPPORT_TICKET_DETAILS = 'SET_SUPPORT_TICKET_DETAILS';
export const CREATE_SUPPORT_TICKET_RESPONS = 'CREATE_SUPPORT_TICKET_RESPONS';

export const SEND_SUPPORT_COMMENT = 'SEND_SUPPORT_COMMENT';
export const SET_NEW_SEND_SUPPORT_COMMENT = 'SET_NEW_SEND_SUPPORT_COMMENT';

export const SUPPORT_TICKET_REOPEN = 'SUPPORT_TICKET_REOPEN';
export const SUPPORT_TICKET_REOPEN_FAILED = 'SUPPORT_TICKET_REOPEN_FAILED';
export const SUPPORT_TICKET_REOPEN_SUCCESS = 'SUPPORT_TICKET_REOPEN_SUCCESS';